# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExoWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExoWeather

  pod 'Alamofire', '~> 5.5'
  pod 'Swinject'

  target 'ExoWeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExoWeatherUITests' do
    # Pods for testing
  end

end
